//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAAOM_Server.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PAAOM_Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Решетка.
        /// </summary>
        public static string Array {
            get {
                return ResourceManager.GetString("Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Центр решетки.
        /// </summary>
        public static string Array_ArrayCenter {
            get {
                return ResourceManager.GetString("Array_ArrayCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на X (м):.
        /// </summary>
        public static string Array_ArrayCenterX {
            get {
                return ResourceManager.GetString("Array_ArrayCenterX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Y (м):.
        /// </summary>
        public static string Array_ArrayCenterY {
            get {
                return ResourceManager.GetString("Array_ArrayCenterY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Z(м):.
        /// </summary>
        public static string Array_ArrayCenterZ {
            get {
                return ResourceManager.GetString("Array_ArrayCenterZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры решетки.
        /// </summary>
        public static string Array_ArrayParametrs {
            get {
                return ResourceManager.GetString("Array_ArrayParametrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество микрофонов.
        /// </summary>
        public static string Array_MicrophonesCount {
            get {
                return ResourceManager.GetString("Array_MicrophonesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Радиус (м).
        /// </summary>
        public static string Array_Radius {
            get {
                return ResourceManager.GetString("Array_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        public static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Среда.
        /// </summary>
        public static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры воздуха.
        /// </summary>
        public static string Environment_AirParametrs {
            get {
                return ResourceManager.GetString("Environment_AirParametrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Температура воздуха (°C).
        /// </summary>
        public static string Environment_AirTemperature {
            get {
                return ResourceManager.GetString("Environment_AirTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень шума (0-1).
        /// </summary>
        public static string Environment_NoiseLevel {
            get {
                return ResourceManager.GetString("Environment_NoiseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость звука (м/с).
        /// </summary>
        public static string Environment_SoundSpeed {
            get {
                return ResourceManager.GetString("Environment_SoundSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Амплитуда.
        /// </summary>
        public static string Graphs_AmplitudeAxis {
            get {
                return ResourceManager.GetString("Graphs_AmplitudeAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спектр.
        /// </summary>
        public static string Graphs_SpectrumButton {
            get {
                return ResourceManager.GetString("Graphs_SpectrumButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время, с.
        /// </summary>
        public static string Graphs_TimeAxis {
            get {
                return ResourceManager.GetString("Graphs_TimeAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить настройки.
        /// </summary>
        public static string MainWindow_ApplySettingsButton {
            get {
                return ResourceManager.GetString("MainWindow_ApplySettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить настройки.
        /// </summary>
        public static string MainWindow_LoadSettingsButton {
            get {
                return ResourceManager.GetString("MainWindow_LoadSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить настройки.
        /// </summary>
        public static string MainWindow_SaveSettingsButton {
            get {
                return ResourceManager.GetString("MainWindow_SaveSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string MainWindow_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры системы.
        /// </summary>
        public static string MainWindow_SystemParametrs {
            get {
                return ResourceManager.GetString("MainWindow_SystemParametrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер ФАР.
        /// </summary>
        public static string MainWindow_Titile {
            get {
                return ResourceManager.GetString("MainWindow_Titile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить графики.
        /// </summary>
        public static string MainWindow_UpdateGraphs {
            get {
                return ResourceManager.GetString("MainWindow_UpdateGraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сеть.
        /// </summary>
        public static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление отправкой данных.
        /// </summary>
        public static string Network_DataSenderController {
            get {
                return ResourceManager.GetString("Network_DataSenderController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Локальный IP.
        /// </summary>
        public static string Network_LocalIP {
            get {
                return ResourceManager.GetString("Network_LocalIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Локальный порт.
        /// </summary>
        public static string Network_LocalPort {
            get {
                return ResourceManager.GetString("Network_LocalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаленный IP.
        /// </summary>
        public static string Network_RemoteIP {
            get {
                return ResourceManager.GetString("Network_RemoteIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаленный порт.
        /// </summary>
        public static string Network_RemotePort {
            get {
                return ResourceManager.GetString("Network_RemotePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интервал отправки (мс).
        /// </summary>
        public static string Network_SendInterval {
            get {
                return ResourceManager.GetString("Network_SendInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить пакет.
        /// </summary>
        public static string Network_SendPacket {
            get {
                return ResourceManager.GetString("Network_SendPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить отчет.
        /// </summary>
        public static string Network_SendReport {
            get {
                return ResourceManager.GetString("Network_SendReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки сервера.
        /// </summary>
        public static string Network_ServerSettings {
            get {
                return ResourceManager.GetString("Network_ServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запустить сервер.
        /// </summary>
        public static string Network_StartServer {
            get {
                return ResourceManager.GetString("Network_StartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановить сервер.
        /// </summary>
        public static string Network_StopServer {
            get {
                return ResourceManager.GetString("Network_StopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверить связь.
        /// </summary>
        public static string Network_TestConnection {
            get {
                return ResourceManager.GetString("Network_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Источник.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Позиция источника.
        /// </summary>
        public static string Source_Pos {
            get {
                return ResourceManager.GetString("Source_Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на X (м):.
        /// </summary>
        public static string Source_PosX {
            get {
                return ResourceManager.GetString("Source_PosX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Y (м):.
        /// </summary>
        public static string Source_PosY {
            get {
                return ResourceManager.GetString("Source_PosY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Z (м):.
        /// </summary>
        public static string Source_PosZ {
            get {
                return ResourceManager.GetString("Source_PosZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Амплитуда.
        /// </summary>
        public static string Source_SignalAmplitude {
            get {
                return ResourceManager.GetString("Source_SignalAmplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Частота (Гц).
        /// </summary>
        public static string Source_SignalFrequency {
            get {
                return ResourceManager.GetString("Source_SignalFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры сигнала.
        /// </summary>
        public static string Source_SignalParametrs {
            get {
                return ResourceManager.GetString("Source_SignalParametrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фаза (рад).
        /// </summary>
        public static string Source_SignalPhase {
            get {
                return ResourceManager.GetString("Source_SignalPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фаза (рад).
        /// </summary>
        public static string Source_SignalPhase1 {
            get {
                return ResourceManager.GetString("Source_SignalPhase1", resourceCulture);
            }
        }
    }
}
